[package]
name = "xv6"
version = "0.0.1"
authors = ["Jeehoon Kang <jeehoon.kang@sf.snu.ac.kr>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "1.0.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
